services:    
  mongodb:    
    image: mongo:latest    
    container_name: chronogaz_mongo_db    
    restart: unless-stopped    
    ports:    
      - "27018:27017"    
    volumes:    
      - mongo_data:/data/db    
      - ./mongo-init:/docker-entrypoint-initdb.d:ro  
    environment:    
      MONGO_INITDB_ROOT_USERNAME: root    
      MONGO_INITDB_ROOT_PASSWORD: chronogaz123    
      MONGO_INITDB_DATABASE: chronogaz_db    
    healthcheck:    
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]    
      interval: 30s    
      timeout: 10s    
      retries: 3    
    
  app:    
    build: ./api    
    container_name: chronogaz_app    
    restart: unless-stopped    
    ports:    
      - "5001:5000"    
    environment:    
      MONGODB_URI: mongodb://chronogaz_user:chronogaz_app_password@mongodb:27017/chronogaz_db?authSource=chronogaz_db    
      NODE_ENV: development    
      PORT: 5000    
    depends_on:    
      mongodb:    
        condition: service_healthy    
    volumes:    
      - ./api:/app    
      - /app/node_modules    
  
  frontend:  
    build: ./client  
    container_name: chronogaz_frontend  
    restart: unless-stopped  
    ports:  
      - "3000:3000"  
    environment:  
      - REACT_APP_API_URL=http://localhost:5001/api
      - REACT_APP_SOCKET_URL=http://localhost:5001 
    volumes:  
      - ./client:/app  
      - /app/node_modules  
    depends_on:  
      - app  
    
volumes:    
  mongo_data:    
    driver: local    
    
networks:    
  default:    
    driver: bridge