version: '3.8'  
  
services:    
  frontend: 
    build: ./client  
    container_name: chronogaz_frontend  
    restart: unless-stopped  
    ports:  
      - "3000:3000"  
    volumes:  
      - ./client:/app  
      - node_modules:/app/node_modules  
    environment:  
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

volumes:
  node_modules: